farm/data/urls.py
from django.urls import path, re_path
from . import views
app_name = 'data'
urlpatterns = [
    path('anode_request/<int:gcg_id>/<int:anode_id>', views.anode_request, name = 'anode_request'),
]

farm/farm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token
urlpatterns = [
    path('admin/', admin.site.urls),
    path('palm/', include("palm.urls")),
    path('data/', include("data.urls")),
    path('accounts/', include('accounts.urls')),
    path('social-account', include('allauth.urls')), # allauth.urls 에 대한 지정을 해주어야 소셜 acess token에 대한 rest_framework token을 반환해준다 존나힘드네 ;;
    path('test_app/', include('test_app.urls')),
    path('accounts/login/', auth_views.login, name = 'login', kwargs = {'template_name' : 'login.html'}),
    path('accounts/logout/', auth_views.logout, name = 'logout', kwargs = {'next_page':settings.LOGIN_URL,}),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-jwt-auth/', obtain_jwt_token),
    path('api-jwt-auth/refresh/', refresh_jwt_token),
    path('api-jwt-auth/verify/', verify_jwt_token),
    path('test_api/', include('test_api.urls', namespace='test_api')),
    path('api-token-auth/', obtain_auth_token),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    # etc
]

farm/palm/urls.py
from django.urls import path, re_path
from . import views
app_name = 'palm'
urlpatterns = [
    path('', views.base, name='base'),
    path('index/', views.index, name = 'index'),

    path('control/', views.control, name = 'control'),
    path('control/log/', views.control_log, name = 'control_log'),

    path('category/', views.category, name = 'category'),
    path('category/<str:category>/record', views.record, name = 'record'),
    path('category/past_record', views.past_record, name = 'past_record'),
    # 아마도 설정페이지가 될 부분
    path('gcg_page/', views.gcg_page, name = 'gcg_info'),
    path('gcg_page/gcg_detail/<str:gcg_serial>', views.gcg_detail, name = 'gcg_detail'),

    path('gcg_page/gcg_detail_2/<str:gcg_serial>', views.gcg_detail_2, name = 'gcg_detail_2'),

    path('snode_page/', views.snode_page, name = 'snode_info'),
    path('snode_page/snode_detail/<str:gcg_serial>/<int:value1>/<int:value2>', views.snode_detail, name = 'snode_detail'),
    path('snode_page/anode_detail/<str:gcg_serial>/<int:value1>/<int:value2>', views.anode_detail, name = 'anode_detail'),
    path('snode_page/anode_control/<str:gcg_serial>/<str:anode_serial>/<int:value2>/<int:value3>/<int:value4>', views.anode_control, name = 'anode_control'),
    # Vegetable_Record 은 시장조사( 시범농장 ) 직전 혹은 진행하면서 개발해도 좋을듯 함
    # etc 설정페이지 데이터페이지 고객센터 등 페이지 추가예정
]

farm/farm/templates/layout.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="kr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel="stylesheet" href="{% static '/css/palm.css' %}">

    {% block style %}
    {% endblock %}
    <link rel="stylesheet" href="{% static '/css/palm.css' %}">

    <!-- 부트스트랩 -->
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static '/bootstrap/vendor/bootstrap/css/bootstrap.min.css' %}">


    <!-- Custom Fonts 아이콘 가져오기 -->
    <link href="{% static '/bootstrap/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- jQuery -->
    <script src="{% static '/bootstrap/vendor/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static '/bootstrap/vendor/bootstrap/js/bootstrap.min.js' %}"></script>


    <script type="text/javascript" src="{% static '/js/vxgplayer-1.7.44.min.js' %}"></script>
    <link rel="stylesheet" href="{% static '/css/vxgplayer-1.7.44.min.css' %}">

  </head>
  <body>

      <div class="wrapper">
        <div class="header">
          <a class="" href="{% url 'palm:base' %}">
            <strong>FarmPalmLABS</strong>
          </a>
        </div>

        <div class="menu">
          <a class="menu-divider" href="{% url 'palm:base' %}"><i class="fa fa-bar-chart-o fa-fw"></i>전체정보</span></a>
          <a class="menu-divider" href="{% url 'palm:control' %}"><i class="fa fa-table fa-fw"></i>제어모드</span></a>

          <a class="menu-divider" href="#"><i class="fa fa-edit fa-fw"></i>세부사항</span></a>
          <a class="menu-divider" href="#"><i class="fa fa-bar-chart-o fa-fw"></i>일지작성</span></a>
          <a href="#"><i class="fa fa-sitemap fa-fw"></i>특이사항</span></a>
        </div>

        <div class="content">
          {% block content %}
          {% endblock %}
        </div>

        <div class="footer">footer</div>

        
      </div>
      <script src="{% static '/js/palm.js' %}"></script>


      </div>
      <script src="{% static '/js/palm.js' %}"></script>

  </body>
</html>

farm/farm/templates/login.html
{% extends "layout.html" %}

{% block content %}

<html>
 <head>
  <title>Login</title>
 </head>
 <body>
  <h2>Login</h2>
   <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
   </form>
 </body>
</html>

{% endblock %}