farm/data/urls.py
from django.urls import path, re_path
from . import views
app_name = 'data'
urlpatterns = [
    path('anode_request/<int:gcg_id>/<int:anode_id>', views.anode_request, name = 'anode_request'),
]

farm/farm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token
urlpatterns = [
    path('admin/', admin.site.urls),
    path('palm/', include("palm.urls")),
    path('data/', include("data.urls")),
    path('accounts/', include('accounts.urls')),
    path('social-account', include('allauth.urls')), # allauth.urls 에 대한 지정을 해주어야 소셜 acess token에 대한 rest_framework token을 반환해준다 존나힘드네 ;;
    path('test_app/', include('test_app.urls')),
    path('accounts/login/', auth_views.login, name = 'login', kwargs = {'template_name' : 'login.html'}),
    path('accounts/logout/', auth_views.logout, name = 'logout', kwargs = {'next_page':settings.LOGIN_URL,}),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-jwt-auth/', obtain_jwt_token),
    path('api-jwt-auth/refresh/', refresh_jwt_token),
    path('api-jwt-auth/verify/', verify_jwt_token),
    path('test_api/', include('test_api.urls', namespace='test_api')),
    path('api-token-auth/', obtain_auth_token),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    # etc
]

farm/palm/urls.py
from django.urls import path, re_path
from . import views
app_name = 'palm'
urlpatterns = [
    path('', views.base, name='base'),
    path('index/', views.index, name = 'index'),

    path('control/', views.control, name = 'control'),
    path('control/log/', views.control_log, name = 'control_log'),

    path('category/', views.category, name = 'category'),
    path('category/<str:category>/record', views.record, name = 'record'),
    path('category/past_record', views.past_record, name = 'past_record'),
    # 아마도 설정페이지가 될 부분
    path('gcg_page/', views.gcg_page, name = 'gcg_info'),
    path('gcg_page/gcg_detail/<str:gcg_serial>', views.gcg_detail, name = 'gcg_detail'),

    path('gcg_page/gcg_detail_2/<str:gcg_serial>', views.gcg_detail_2, name = 'gcg_detail_2'),

    path('snode_page/', views.snode_page, name = 'snode_info'),
    path('snode_page/snode_detail/<str:gcg_serial>/<int:value1>/<int:value2>', views.snode_detail, name = 'snode_detail'),
    path('snode_page/anode_detail/<str:gcg_serial>/<int:value1>/<int:value2>', views.anode_detail, name = 'anode_detail'),
    path('snode_page/anode_control/<str:gcg_serial>/<str:anode_serial>/<int:value2>/<int:value3>/<int:value4>', views.anode_control, name = 'anode_control'),
    # Vegetable_Record 은 시장조사( 시범농장 ) 직전 혹은 진행하면서 개발해도 좋을듯 함
    # etc 설정페이지 데이터페이지 고객센터 등 페이지 추가예정
]

farm/palm/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Gcg 모델 정의 Gcg
# Gcg와 GcgInfo를 나눌필요는 없어보임 그이유는 자주 수정될 이유가 없는 테이블이고
# 수정된 부분도 인포의 일부분이기때문에 이부분을 로그로 남김 ex) sensing_periode/ Error
# AllHouseCctv 모델 정의
class AllHouseCctv(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    cctv_url = models.CharField(max_length=1000, blank=True)
    cctv_ip = models.CharField(max_length=1000, blank=True)
    def __str__(self):
        return 'All House Cctv of user : {}'.format(self.user.username)

class Gcg(models.Model):
    STATE_TYPE = (
        ('n', 'Normal'),
        ('b', 'Battery_Error'),
        ('v', 'Voltage_Error'),
        ('c', 'Communication_Error'),
        ('u', 'Unknown Error'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    serial_num = models.CharField(default=0, max_length=100)
    node_num = models.IntegerField(default=0)
    node_group = models.IntegerField(default=0)
    # 이부분은 node_id가 들어갈 부분인데 gcg와 1:N관계로 있는 snode들의 그룹을 의미하므로 없어도 될 항복
    sensing_periode = models.DateTimeField(auto_now_add=True)
    gcg_state = models.CharField(max_length=1, choices=STATE_TYPE, blank=True)
    comm_error_num = models.IntegerField(default=0)
    service_error_num = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return 'Gcg {} of {}'.format(self.id, self.user.username)
class GcgLog(models.Model):
    # Gcg Info 중에서 로그로 남길부분들을 정하여서 적는것이 좋을듯
    # 이는 Gcg와의 통신로그와 구별시킬지, 합쳐도 무방할지
    # 합쳐도 무방하다고 생각 자주 수정될 테이블은 아니기때문에
    pass

# GcgCctv 모델 정의 type 으로 구분
class GcgCctv(models.Model):
    CCTV_TYPE = (
        ('i', 'inside'),
        ('o', 'outside'),
    )
    gcg = models.ForeignKey('Gcg', on_delete=models.PROTECT)
    cctv_type = models.CharField(max_length=1, choices=CCTV_TYPE)
    # 이는 나중에 Validate 함수를 거쳐 검사를 하게된다.
    cctv_url = models.CharField(max_length=1000, blank=True)
    cctv_ip = models.CharField(max_length=1000, blank=True)
    def __str__(self):
        return '{} Cctv if user : {}, gcg : {}'.format(self.get_cctv_type_display(), self.gcg.user.username, self.gcg.id)

# Snode 모델 정의
# Snode와 SnodeInfo를 구분할 필요는 마찬가지로 없다고 생각
class Snode(models.Model):
    STATE_TYPE = (
        ('n', 'Normal'),
        ('s', 'Sensor_Error'),
        ('b', 'Battery_Error'),
        ('v', 'Voltage_Error'),
        ('c', 'Communication_Error'),
        ('u', 'Unknown_Error'),
    )
    MONITOR_TYPE = (
        ('p', 'Passive'),
        ('e', 'Emergency'),
    )
    SNODE_TYPE = (
        ('t', 'Temperature'),
        ('h', 'Humidity'),
        ('th', 'Temperature_Humidity'),
        ('l', 'Light'),
        ('ws', 'Wind_Speed'),
        ('wd', 'Wind_Direction'),
        ('rf', 'Rain_Fall'),
        ('st', 'Soil_Temperature'),
        ('sh', 'Soil_Humidity'),
        ('ph', 'pH'),
        ('ec', 'EC'),
    )
    gcg = models.ForeignKey('Gcg', on_delete=models.PROTECT, blank=True)
    snode_type = models.CharField(max_length=2, choices=SNODE_TYPE)
    serial_num = models.CharField(max_length=100)
    sw_ver = models.IntegerField(default=0)
    register_num = models.IntegerField(default=0)
    register_date = models.DateTimeField(auto_now_add=True)
    node_state = models.CharField(max_length=1, choices=STATE_TYPE, blank=True)
    monitor_mode = models.CharField(max_length=1, choices=MONITOR_TYPE, blank=True)
    comm_error_num = models.IntegerField(default=0)
    service_error_num = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return 'Snode {} of {}, {}'.format(self.id, self.get_snode_type_display() , self.gcg)

class SnodeValue(models.Model):
    SNODE_TYPE = (
        ('t', 'Temperature'),
        ('h', 'Humidity'),
        ('th', 'Temperature_Humidity'),
        ('l', 'Light'),
        ('ws', 'Wind_Speed'),
        ('wd', 'Wind_Direction'),
        ('rf', 'Rain_Fall'),
        ('st', 'Soil_Temperature'),
        ('sh', 'Soil_Humidity'),
        ('ph', 'pH'),
        ('ec', 'EC'),
    )
    snode = models.ForeignKey('Snode', on_delete=models.PROTECT)
    snode_type = models.CharField(max_length=2, choices=SNODE_TYPE)
    snode_value = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    # snode_value = models.IntegerField()
    # CharField 를 선택한 이유는 한개의 센서가 다수의 센싱값을 보내기때문
    def __str__(self):
        return 'Value {} of Snode {}'.format(self.snode_value, self.snode.serial_num)

class SnodeLog(models.Model):
    # 이도 마찬가지 Snode에 관한 로그기록
    # 이도 나중에 통합될수도
    pass
# Anode 모델 정의
# 마찬가지로 Anode 와 AnodeInfo를 구분할 필요는 없다고 생각

class Anode(models.Model):
    STATE_TYPE = (
        ('n', 'Normal'),
        ('s', 'Sensor_Error'),
        ('b', 'Battery_Error'),
        ('v', 'Voltage_Error'),
        ('c', 'Communication_Error'),
        ('u', 'Unknown_Error'),
    )
    OPERATING_TYPE = (
        ('p', 'Passive'),
        ('e', 'Emergency'),
    )
    ANODE_TYPE = (
        ('oc', 'Open_Close_Motor'),
        ('ef', 'Extractor_Fan'),
        ('wm', 'Watering_Motor'),
        ('ns', 'Nutrient_Supply'),
        ('lc', 'Light_Control'),
        ('cc', 'Co2_Control'),
        ('dh', 'Dehumidifier'),
        ('hf', 'Humidifier'),
        ('ve', 'Valve_Equipment'),
    )
    gcg = models.ForeignKey('Gcg', on_delete=models.PROTECT, blank=True)
    anode_type = models.CharField(max_length=2, choices=ANODE_TYPE)
    serial_num = models.CharField(max_length=100)
    sw_ver = models.IntegerField(default=0)
    register_num = models.IntegerField(default=0)
    register_date = models.DateTimeField(auto_now_add=True)
    node_state = models.CharField(max_length=1, choices=STATE_TYPE, blank=True)
    operating_mode = models.CharField(max_length=1, choices=OPERATING_TYPE, blank=True)
    comm_error_num = models.IntegerField(default=0)
    service_error_num = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return 'Anode {} of {}, {}'.format(self.id, self.get_anode_type_display(), self.gcg)

class AnodeValue(models.Model):
    ANODE_TYPE = (
        ('oc', 'Open_Close_Motor'),
        ('ef', 'Extractor_Fan'),
        ('wm', 'Watering_Motor'),
        ('ns', 'Nutrient_Supply'),
        ('lc', 'Light_Control'),
        ('cc', 'Co2_Control'),
        ('dh', 'Dehumidifier'),
        ('hf', 'Humidifier'),
        ('ve', 'Valve_Equipment'),
    )
    anode = models.ForeignKey('Anode', on_delete=models.PROTECT)
    anode_type = models.CharField(max_length=2, choices = ANODE_TYPE)
    anode_value = models.CharField(max_length=100)
    # anode_value = models.CharField()
    # 마찬가지의 이유
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return 'Value {} of Anode {}'.format(self.anode_value, self.anode.serial_num)

class AnodeLog(models.Model):
    # 이것역시 보류사항
    anode = models.ForeignKey('Anode', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
# Vegetable Record 모델 정의

class Category(models.Model):
    VEGI_TYPE = (
        ('aaa', '오이'),
        ('aab', '딸기'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    category = models.CharField(max_length=3, choices=VEGI_TYPE, default=None)
    def __str__(self):
        return 'Category : {}'.format(self.get_category_dispaly())

class Record(models.Model):
    category = models.ForeignKey('Category', on_delete=models.PROTECT, default=None)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
# Demo 버전의 항목이 정해지면 그때 추가하여 진행
# Create your models here.

farm/palm/templates/settings/gcg_detail.html
{% extends "settings/layout.html" %}
{% block content %}
<h3>gcg_id = {{gcg_id}}</h3>
<h3>sw_ver = {{sw_ver}}</h3>
<h3>node_num = {{node_num}}</h3>
{% for node in node_info %}

{% if forloop.counter < node_num %}
<h3>node_{{forloop.counter}}_info : {{ node | length }}</h3>
{% endif %}

<h3>node_{{forloop.counter}}_info : {{node}}</h3>

{% endfor %}
<h3>sensing_period : {{sensing_period_hour}}:{{sensing_period_min}}:{{sensing_period_sec}}</h3>
<h3>gcg_state : {{gcg_state}}</h3>
<h3>comm_error_num : {{comm_error_num}}</h3>
<h3>service_error_num : {{service_error_num}}</h3>
<h3>etc : {{etc}}</h3>
<<<<<<< HEAD


{% endblock %}
=======
{% endblock %}
>>>>>>> 2537851... rtsp  크롬 확장프로그램 이용 cctv화면 송출

farm/palm/templates/settings/gcg_detail_2.html
{% extends "settings/layout.html" %}
{% block content %}

<div class="gcg_page_body" style="
padding-left: 50px;
width: 100%;
height: 100%; ">

  <h3>통합제어기 일련번호 = {{gcg_id}}</h3>
  <h3>노드 개수 = {{node_num|get_digit:"1" }}개</h3>
  <table border='1' style="
    border-collapse:collapse;
    table-layout: auto;
    font-size: 25px;
    text-align: center;
    vertical-align: middle;
  ">
    <thead>
        <th style="padding: 10px 40px;">노드번호</th>
        <th style="padding: 10px 40px;">종류</th>
        <th style="padding: 10px 40px;">일련번호</th>
    </thead>
    <tbody class="node_info" onload="node_info({{ node_info }})">
      {% for node in node_info %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td> <span class="node_type">{{ node.1 }}</span> </td>
          <td> <span class="node_id"></span>{{ node.0 }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

farm/palm/templates/settings/gcg_page.html
{% extends "settings/layout.html" %}
{% block content %}
<p></p>
{% for gcg in gcg %}
<a href="{% url "palm:gcg_detail" gcg.serial_num %}" class = "btn btn-primary">gcg 일련번호 : {{gcg.serial_num}} 정보요청</a>
{% endfor %}

{% for gcg in gcg %}
<a href="{% url "palm:gcg_detail_2" gcg.serial_num %}" class = "btn btn-primary">gcg 일련번호 : {{gcg.serial_num}} 정보요청</a>
{% endfor %}
{% endblock %}

{% endblock %}

farm/palm/templates/settings/layout.html
{% extends "layout.html" %}

farm/palm/templates/settings/snode_detail.html
{% extends "settings/layout.html" %}
{% block content %}
<h3>gcg_id = {{gcg_id}}</h3>
<h3>sw_ver = {{sw_ver}}</h3>
<h3>node_num = {{node_num}}</h3>
{% for node in node_info %}
<h3>node_{{forloop.counter}}_info : {{node}}</h3>
{% endfor %}
<h3>sensing_period : {{sensing_period_hour}}:{{sensing_period_min}}:{{sensing_period_sec}}</h3>
<h3>gcg_state : {{gcg_state}}</h3>
<h3>comm_error_num : {{comm_error_num}}</h3>
<h3>service_error_num : {{service_error_num}}</h3>
<h3>etc : {{etc}}</h3>
{% endblock %}

farm/palm/templates/settings/snode_page.html
{% extends "settings/layout.html" %}
{% block content %}
<p></p>
{% for gcg in gcg %}
<h1>{{gcg.serial_num}} 통합제어기 노드</h1>
{# value1 value2 value3 을 넘겨준다 #}
<a href="{% url "palm:snode_detail" gcg.serial_num 1 8 %}" class = "btn btn-primary" >통합제어기 {{gcg.serial_num}}에 연결된 전체 센서노드 정보 요청</a>
<a href="{% url "palm:anode_detail" gcg.serial_num 1 1 %}" class = "btn btn-primary">통합제어기 {{gcg.serial_num}}에 연결된 전체 제어노드 정보 요청</a>
<p></p>
<p></p>
{% for anode in gcg.anode_set.all %}
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 1 1 0 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 전체 On</a>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 0 1 0 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 전체 Off</a>
<p></p>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 1 2 0 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 1 On</a>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 0 2 0 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 1 Off</a>
<p></p>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 1 2 1 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 2 On</a>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 0 2 1 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 2 Off</a>
<p></p>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 1 2 2 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 3 On</a>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 0 2 2 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 3 Off</a>
<p></p>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 1 2 3 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 4 On</a>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 0 2 3 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 4 Off</a>
<p></p>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 1 2 4 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 5 On</a>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 0 2 4 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 5 Off</a>
<p></p>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 1 2 5 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 6 On</a>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 0 2 5 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 6 Off</a>
<p></p>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 1 2 6 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 7 On</a>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 0 2 6 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 7 Off</a>
<p></p>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 1 2 7 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 8 On</a>
<a href="{% url "palm:anode_control" gcg.serial_num anode.serial_num 0 2 7 %}" class = "btn btn-primary">{{anode.serial_num}} 제어노드 Actuator 8 Off</a>
<hr>
{% endfor %}

{% endfor %}

{% endblock %}